# Generated by Django 5.2.1 on 2025-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
