# Generated by Django 5.2.1 on 2025-06-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_size_name_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
